# frozen-string-literal: true

source 'https://rubygems.org'
ruby '2.5.0'

gem 'devise'
gem 'jbuilder', '~> 2.0'
gem 'pg', '~> 0.21'
gem 'puma'
gem 'rails', '5.2.0'
gem 'redis'

# Needed for Active Storage
# gem 'aws-sdk-s3', require: false
# gem 'image_processing', '~> 1.2'

gem 'autoprefixer-rails'
gem 'bootstrap' # bootstrap 4
gem 'font-awesome-sass'
gem 'pundit'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'webpacker'

group :development do
  gem 'bootsnap', require: false
  gem 'letter_opener'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'database_cleaner'
  gem 'faker'
  gem 'rspec'
  gem 'simplecov'
  gem 'vcr'
  gem 'webmock'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'listen', '~> 3.0.5'
  gem 'pry-byebug'
  gem 'pry-rails'
end
